spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Binance Smart Chain (BSC) Network URL
bsc:
  network:
    url: https://data-seed-prebsc-1-s1.binance.org:8545/

wallet:
  keystore:
    directory: ${user.home}/keystore

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    s3:
      bucket: ${KEYSTORE_BUCKET}
    region:
      static: ap-northeast-2
    stack:
      auto: false

contract:
  token:
    address: ${CONTRACT_TOKEN_ADDRESS}
  funding:
    address: ${CONTRACT_FUNDING_ADDRESS}
  admin:
    private-key: ${CONTRACT_ADMIN_PRIVATEKEY}

service:
  user:
    url: https://picktartup.com
  coin:
    url: https://picktartup.com
